<a href="https://colab.research.google.com/github/mhtefe/deepLearning/blob/master/0_hello_torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
import numpy as np
import torch
print(torch.__version__)

1.5.1+cu101


In [ ]:
#simplify line seperator
sep = lambda : print('-'*20)

In [ ]:
#%% simple tensors and randoms
np_ones = np.ones( (2,2) )
print(np_ones)

torch_ones = torch.ones( (2,2) )
print(torch_ones)

sep()

np_rand = np.random.rand(2, 2)
print(np_rand)

torch_rand = torch.rand(2, 2)
print(torch_rand)

[[1. 1.]
 [1. 1.]]
tensor([[1., 1.],
        [1., 1.]])
[[0.73720702 0.60587605]
 [0.13538413 0.15457905]]
tensor([[0.1209, 0.8735],
        [0.8445, 0.0647]])


In [ ]:
#%% numpy bridge. we can transfer values from numpy to torch by '.from_numpy()'
print('type of np_ones', type(np_ones))
torch_tensor = torch.from_numpy(np_ones)
print('type of torch_tensor: ', type(torch_tensor))

sep()
# Data types matter: intentional error
np_array_new = np.ones((2, 2), dtype=np.int8)
print(np_array_new.dtype)
torch_arrray_int8 = torch.from_numpy(np_array_new)
print(torch_arrray_int8.type()) 

type of np_ones <class 'numpy.ndarray'>
type of torch_tensor:  <class 'torch.Tensor'>
--------------------
int8
torch.CharTensor


In [ ]:
#%% seed
np.random.seed(0)
m_np = np.random.rand(2, 2)
print(m_np)

sep()

# Torch Seed
torch.manual_seed(0)
m_tr = torch.rand(2, 2)
print(m_tr)

# When you conduct deep learning experiments, 
# typically you want to use GPUs to accelerate your computations and fixing seed 
# for tensors on GPUs is different from CPUs as we have done above.
if torch.cuda.is_available():
    print('seed set for cuda')
    torch.cuda.manual_seed_all(0)


[[0.5488135  0.71518937]
 [0.60276338 0.54488318]]
--------------------
tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])


In [ ]:
#%% torch datatypes
np_array_new = np.ones((2, 2), dtype=np.int32)
print( torch.from_numpy(np_array_new) )

np_array_new = np.ones((2, 2), dtype=np.uint8)
print( torch.from_numpy(np_array_new) )

np_array_new = np.ones((2, 2), dtype=np.float64)
print( torch.from_numpy(np_array_new) )

sep()
torch_tensor = torch.ones(2, 2)
print(type(torch_tensor))
torch_to_numpy = torch_tensor.numpy()
print( type(torch_to_numpy) )

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)
tensor([[1, 1],
        [1, 1]], dtype=torch.uint8)
tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)
--------------------
<class 'torch.Tensor'>
<class 'numpy.ndarray'>


In [ ]:
#%% device
# CPU
tensor_cpu = torch.ones(2, 2)

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)

tensor_cpu.to(device)
tensor_cpu.cpu()

cpu


tensor([[1., 1.],
        [1., 1.]])

We can resize the tensor with 'view()' method. view should preserve dimensions

In [ ]:
#%% resize tensor
a = torch.ones(2, 2)
print('a is: ', a)
print('a size: ', a.size())

sep()

b = a.view(4) # view(3) would give error
print(b)

print(a.view(4).size())

a is:  tensor([[1., 1.],
        [1., 1.]])
a size:  torch.Size([2, 2])
--------------------
tensor([1., 1., 1., 1.])
torch.Size([4])
